<h1>System Logins</h1>

<?php if (count($this->paginator)): ?>
    <div class="container-fluid row ">
        <div class="col-xs-1"> 
            <?php 
            if ($order == "ASC") {
                $newOrder = "DESC";
            } elseif ($order == "DESC") {
                $newOrder = "ASC";
            } 
           
            ?>
            <a href="<?php echo $this->url('admin/user', array('module' => 'admin' , 'controller' => 'user','action' => 'index',  'page' => $page, 'order_by' => 'id', 'order' => $newOrder)); ?>" title="ID">
                ID
            </a>
        </div>
        <div class="col-xs-2">
            <a href="<?php echo $this->url('admin/user', array('module' => 'admin' , 'controller' => 'user','action' => 'index',  'page' => $page, 'order_by' => 'first_name', 'order' => $newOrder)); ?>" title="First Name">
            
                First Name
            </a>
        </div>
        <div class="col-xs-2">
            <a href="<?php echo $this->url('admin/user', array('module' => 'admin' , 'controller' => 'user','action' => 'index',  'page' => $page, 'order_by' => 'last_name', 'order' => $newOrder)); ?>" title="Last Name" >
                Last Name
            </a>
        </div>
        <div class="col-xs-3">
            <a href="<?php echo $this->url('admin/user', array('module' => 'admin' , 'controller' => 'user','action' => 'index',  'page' => $page, 'order_by' => 'email', 'order' => $newOrder)); ?>" title="Email" >
                Email
            </a>
        </div>
        <div class="col-xs-1">Edit</div>
        <div class="col-xs-1">Delete</div>
    </div>
        <?php foreach ($this->paginator as $id => $item): ?>
            <div class="container-fluid  row">
                <div class="col-xs-1"><?php echo $item['id'] ?></div>
                <div class="col-xs-2"><?php echo $item['first_name']; ?></div>
                <div class="col-xs-2"><?php echo $item['last_name']; ?></div>
                <div class="col-xs-3"><?php echo $item['email']; ?></div>
                <div class="col-xs-1">
                    <a href="<?php echo $this->url('admin/user', array('module' => 'admin' , 'controller' => 'user','action' => 'update', 'id' => $item['id'])); ?>" title="" >
                        Edit
                    </a>
                </div>
                <div class="col-xs-1">
                    <a href="<?php echo $this->url('admin/user', array('module' => 'admin' , 'controller' => 'user','action' => 'delete', 'id' => $item['id'])); ?>" title="" >
                        Delete
                    </a>
                </div>
            </div>
        <?php endforeach ?>
<?php endif; ?>

<!-- call pagination control view script  -->
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'pagination', array('page' => $page, 'order_by' => $order_by, 'order' => $order,'route' => 'admin/user','controller' => 'user')); ?>