<h2 class="user_icon p_title">User Profile Update</h2>

<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php echo $this->formRow($form->get('id')); ?>
<div class="control-input">
    <?php echo $this->formRow($form->get('user_name')); ?>
</div>
<?php if($id === null) : ?>
<div class="control-input">
    <?php echo $this->formRow($form->get('user_password')); ?>
</div>
<?php endif; ?>
<div class="control-input">
    <?php echo $this->formRow($form->get('email')); ?>
</div>
<div class="control-input">
    <?php echo $this->formRow($form->get('role_id')); ?>
</div>
<div class="control-input">
    <?php echo $this->formRow($form->get('first_name')); ?>
</div>
<div class="control-input">
    <?php echo $this->formRow($form->get('last_name')); ?>
</div>
<div class="control-input">
    <?php echo $this->formRow($form->get('image')); ?>
</div>
<div class="control-input ">
    <label>&nbsp;</label>
    <div class="btn btn-large btn-block btn-success">
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
    <div class="btn btn-small btn-block cancel">
        <?php echo $this->formRow($form->get('cancel')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>