<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Test Project Management System ' . $this->translate('Sticky Notes'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>



        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/public/css/common.css')
                ->prependStylesheet($this->basePath() . '/public/admin/css/style.css')
                ->prependStylesheet($this->basePath() . '/public/admin/css/reset.css')
                ->prependStylesheet($this->basePath() . '/public/css/flat-ui.css')
        ?>


        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/public/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/public/admin/js/application.js')
                ->prependFile($this->basePath() . '/public/js/jquery-ui-1.10.3.custom.min.js')
                ->prependFile($this->basePath() . '/public/js/jquery-1.8.3.min.js');
        ?>
    </head>
    <body class="row-fluid">
        <div id="main">

            <div id="left">

                <div id="logo">

                </div>

                <div id="tools">
                    <?php
                    $children = $this->viewModel()->getCurrent()->getChildren();
                    $child = $children[0];
                    //$authService = $this->serviceLocator->get('auth_service');
                    $class = "select";
                    ?>

                    <ul>
                        <a href="#">
                            <li id="dashboard" class="<?php  echo ($child->dashboard === true) ?  $class  : ""; ?>">
                                Dashboard
                            </li>
                        </a>
                        <a href="<?php echo $this->url('admin/default', array('action' => 'index', 'controller' => 'user')); ?>">
                            <li id="users" class="<?php  echo ($child->user === true) ?  $class  : ""; ?>">
                                Users
                            </li>
                        </a>
                        
                        <a href="<?php echo $this->url('admin/default', array('action' => 'update', 'controller' => 'role', 'id' => $child->userSessionData['id'])); ?>">
                            <li id="user-roles" class="<?php  echo ($child->user_roles === true) ?  $class  : ""; ?>">
                                User Roles
                            </li>
                        </a>
                        <!--					<a href="#"><li id="sayfalar">Sayfalar</li></a>
                                                                <a href="#"><li id="baglantilar">Bağlantılar</li></a>
                                                                <a href="#"><li id="yorumlar">Yorumlar <span class="number">7</span></li></a>
                                                                <a href="#"><li id="bilesenler">Bileşenler</li></a>
                                                                <a href="#"><li id="eklentiler">Eklentiler <span class="number">2</span></li></a>
                                                                <a href="#"><li id="kullanicilar">Kullanıcılar</li></a>
                                                                <a href="#"><li id="araclar">Araçlar</li></a>
                                                                <a href="#"><li id="ayarlar">Ayarlar</li></a>-->
                    </ul>

                </div>

                <div id="keep">

                </div>

            </div>

            <div id="right">

                <div id="header">

                    <div id="plus">

                        <a href="#">
                            <span id="arti"></span>
                        </a>

                    </div>

                    <div id="other">

                        <a href="#"><span id="bulut"></span></a>
                        <a href="#"><span id="yorum"></span><div id="yorum_sayi">7</div></a>
                        <a href="#"><span id="zil"></span></a>
                        <a href="#"><span id="wordpress"></span></a>

                    </div>

                </div>

                <div id="body">

                   

                    

                    
<?php echo $this->content; ?>


                 

                </div>

            </div>
            
                    <div id="footer">

                        <div id="f_left">
                            Developed by <a href="" >Kdecom</a>
                        </div>

                        <div id="f_right">
                            <ul>
                                <li><a href="http://anibor.digeryuzu.com"><span id="user"><font>anibor</font></span></a></li>
                                <li><a href="#"><span id="setting"></span></a></li>
                                <li><a href="<?php echo $this->url('logout'); ?>"><span id="exit"></span></a></li>
                            </ul>
                        </div>

<?php echo $this->inlineScript() ?>
                    </div>

    </body>
</html>


