<?php //$this->headLink()->prependStylesheet($this->basePath() . '/public/module/report/timesheet.css'); ?>
<?php $this->headScript()->prependFile($this->basePath() . '/public/module/report/report.js'); ?>


<h2 class="user_icon p_title">Hours Worked By Employees</h2>

<?php

$form->prepare();
echo $this->form()->openTag($form);
?>
<?php //echo $this->formRow($form->get('id')); ?>

<div class="control-input">
	<?php  echo $this->formLabel($form->get('employee')); ?>
    <?php echo $this->formElement($form->get('employee'));?>
</div>
    <?php //echo $this->formRow($form->get('employee')); ?>
<div class="control-input">
    <?php echo $this->formRow($form->get('from_date')); ?>
</div>
<div class="control-input">
    <?php echo $this->formRow($form->get('to_date')); ?>
</div>

<div class="control-input">
	<?php  echo $this->formLabel($form->get('group_by')); ?>
    <?php echo $this->formElement($form->get('group_by'));?>
</div>

<div class="control-input ">
    <label>&nbsp;</label>
    <div class="btn btn-large btn-block btn-success">
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>