<?php $this->headLink()->prependStylesheet($this->basePath() . '/public/module/report/report.css'); ?>
<?php $this->headScript()->prependFile($this->basePath() . '/public/module/report/report.js'); ?>


<h2 class="user_icon p_title">Hours Worked By Employees</h2>

<?php if(!is_null($timesheetRows)) :?>

<div class='timesheetRows'>
	<ul>
		<?php foreach ($timesheetRows as $i => $timesheet): ?>
			<li>
				<span class='start_time'>
				<?php  echo date('d-m-Y H:m',strtotime($timesheet->start_time));?>
				</span>
				<span class='end_time'>
				<?php  echo date('d-m-Y H:m',strtotime($timesheet->end_time));?>
				</span>
				<span class='note_text'>
				<?php  echo $timesheet->notes;?>
				</span>
			
			</li>
		<?php endforeach; ?>
	</ul>

</div>




<?php else: ?>
<?php

$form->prepare();
echo $this->form()->openTag($form);
?>
<?php //echo $this->formRow($form->get('id')); ?>

<div class="control-input">
	<?php  echo $this->formLabel($form->get('employee')); ?>
    <?php echo $this->formElement($form->get('employee'));?>
</div>
    <?php //echo $this->formRow($form->get('employee')); ?>
<div class="control-input">
    <?php echo $this->formRow($form->get('from_date')); ?>
</div>
<div class="control-input">
    <?php echo $this->formRow($form->get('to_date')); ?>
</div>

<div class="control-input">
	<?php  echo $this->formLabel($form->get('group_by')); ?>
    <?php echo $this->formElement($form->get('group_by'));?>
</div>

<div class="control-input ">
    <label>&nbsp;</label>
    <div class="btn btn-large btn-block btn-success">
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<?php endif; ?>