<div class="grid_content">
    
    <div class="Header_titles">
        <h1>Projects</h1>
        <div class="add_link">
            <a href="<?php
                echo $this->url()
                        ->makeUrl(array(
                            'module' => 'workflow',
                            'controller' => 'task',
                            'action' => 'edit'
                        ));
                ?>">Add Task</a>
        </div>
    </div>
    <div class="table">
        <div class="tr header_title">
            <div class="td">
                ID
            </div>
            <div class="td">
                Task Name
            </div>
            <div class="td">
                Task Due Date
            </div>
            <div class="td">
                View
            </div>
            <div class="td">
                Edit
            </div>
            <div class="td">
                Delete
            </div>
        </div>

        <?php
        foreach ($this->paginator as $record) {
            ?>

            <div class="tr">
                <div class="td">
                    <?php
                    echo $record->id;
                    ?>
                </div>
                <div class="td">
                    <?php
                    echo $record->task_name;
                    ?>
                </div>
                <div class="td">
                    <?php
                    echo date('d-m-Y',strtotime($record->task_due_date_time));
                    ?>
                </div>
                <div class="td">
                    <a href="<?php
                echo $this->url()->makeUrl(array(
                                        'module' => 'workflow',
                                        'controller' => 'task',
                                        'action' => 'view',
                                        'id' => $record->id
                                    ));
                ?>" title="edit">View</a>
                </div>
                <div class="td">
                    <a href="<?php
                echo $this->url()->makeUrl(array(
                                        'module' => 'workflow',
                                        'controller' => 'task',
                                        'action' => 'edit',
                                        'id' => $record->id
                                    ));
                ?>" title="edit">edit</a>
                </div>
                <div class="td">
                    delete
                </div>
            </div>
            <?php
        }
        ?>

    </div>
    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml');
    ?>
</div>