<h2>Front End</h2>
<div class="row">
    <div class="span2"></div>
    <div class="span1">View</div>
    <div class="span1">Create/Edit</div>
    <div class="span1">Delete</div>
    
</div>
<div class="row access_box">
    <div class="span2 access_title">Employee</div>
    <div class="span1"><input type="checkbox" data-toggle="switch" name="access[employee][view]" /></div>
    <div class="span1"><input type="checkbox" data-toggle="switch" name="access[employee][create-edit]" /></div>
    <div class="span1"><input type="checkbox" data-toggle="switch" name="access[employee][delete]" /></div>
</div>

<h2>Admin</h2>

<div class="row">
    <div class="span2"></div>
    <div class="span1">View</div>
    <div class="span1">Create/Edit</div>
    <div class="span1">Delete</div>
    
</div>
<div class="row access_box">
    <div class="span2 access_title">Login</div>
    <div class="span1"><input type="checkbox" data-toggle="switch" name="access[user][index]" /></div>
    <div class="span1"><input type="checkbox" data-toggle="switch" name="access[user][update]" /></div>
    <div class="span1"><input type="checkbox" data-toggle="switch" name="access[user][delete]" /></div>
</div>