<h2 class="user_icon p_title"><?php echo $title; ?></h2>

<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php echo $this->formRow($form->get('id')); ?>
<p style='padding-left: 200px;'> You can add contact type as client, customers, dealers and etc.</p>
<div class="control-input">
    <?php echo $this->formRow($form->get('contact_type_name')); ?>
</div>

<div class="control-input ">
    <label>&nbsp;</label>
    <div class="btn btn-large btn-block btn-success">
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>