<?php
$this->headLink()->prependStylesheet(APPLICATION_URL . '/public/application/user/timesheet.css');
$this->headScript()->prependFile(APPLICATION_URL . '/public/application/user/timesheet.js');
?>
<div class="multirow_container">
    <form id="<?php echo $this->form->getId(); ?>" action="<?php echo$this->form->getAction(); ?>" 
          name="<?php echo $this->form->getName(); ?>" 
          type="<?php echo $this->form->getMethod(); ?>" >
        <div class="multi_row_title">
            <h1>Timesheet</h1>
            <div class="date_link">
                <a href="" class="timesheet_date"><?php echo $this->date; ?></a>
                <input type="text" name="date" value="<?php echo $this->date; ?>" />
            </div>
             
        </div>
        <div class="multi_row_data">
            <div class="tr header_title">

                <div class="start_time title">
                    Start time
                </div>
                <div class="end_time title">
                    End Time
                </div>
                <div class="desc_of_task title">
                    Description of task
                </div>
            </div>

            <div class="timesheet_rows forms_container">

                <div class="form_row">
                    <?php
                    foreach($this->form->getDisplayGroups() as $group) {
                        echo $group;
                    }
                    ?>
                    <?php //echo $this->form->getDisplayGroup('FormElemts'); ?>
                </div>


            </div>
            <div class="add_new_row_link">
                <a href="">add row</a>
            </div>
            <div class="save_button">
                <a class="btn savebtn" href="">Save</a>
            </div>
        </div>
    </form>
</div>