<H1> Roles </H1>

<?php if (count($this->paginator)): ?>
    <div class="container-fluid row">
        <div class="col-xs-1"> ID</div>
        <div class="col-xs-2">Role Name</div>
        <div class="col-xs-1">Edit</div>
        <div class="col-xs-1">Delete</div>
    </div>
    <?php foreach ($this->paginator as $idx => $item): ?>
    	
        <div class="container-fluid row">
            <div class="col-xs-1"><?php echo $item['id'] ?></div>
            <div class="col-xs-2"><?php echo $item['role_name']; ?></div>
            <div class="col-xs-1">
                <a href="<?php echo $this->url('admin/role', array('module' => 'admin', 'controller' => 'role', 'action' => 'update', 
                			'id' => $item['id'])); ?>" title="" >
                    Edit
                </a>
            </div>
            <div class="col-xs-1">
                <a class="delete" href="<?php echo $this->url('admin/role', array('module' => 'admin', 'controller' => 'role', 'action' => 'delete', 'id' => $item['id'])); ?>" title="" >
                    Delete
                </a>
            </div>
        </div>
    <?php endforeach ?>
<?php endif; ?>

<!-- call pagination control view script  -->
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'pagination', array('page' => $page, 'order_by' => $order_by, 'order' => $order,'route' => 'admin/role','controller' => 'role')); ?>