<div id="footer">
    <div id="footer-content">
        <ul class="bottom-menu"> 
            <li><a href="">Home</a></li>
            <li class="page_item page-item-127"><a href="">About Us</a></li>
            <li class="page_item page-item-130"><a href="">Contact Us</a></li>
            <li class="page_item page-item-238 current_page_item"><a href="">Product Details</a></li>
            <li class="page_item page-item-135"><a href="">Request a Quote</a></li>
            <li class="page_item page-item-7"><a href="">Testimonials</a></li>
        </ul>			
        <p id="copyright">Designed by  <a title="Elegant Themes" href="">Kdecom</a></p>
    </div> <!-- end #footer-content -->
</div>