
      <div class="container">
        <div class="row">
          <div class="span7">
            <h3 class="footer-title">Subscribe</h3>
            <p>Do you like this freebie? Want to get more stuff like this?<br/>
              Subscribe to Kdecom blogs and updates to stay tuned on great programming skills.<br/>
              Go to: <a href="http://www.kdecom" target="_blank">KDecom.com</a>
            </p>

           
          </div> <!-- /span8 -->

          <div class="span5">
            <div class="footer-banner">
              <h3 class="footer-title">Get Flat UI Pro</h3>
              <ul>
                <li>Tons of Basic and Custom UI Elements</li>
                <li>A Lot of Useful Samples</li>
                <li>Bootstrap Based HTML/CSS/JS Layout</li>
              </ul>
              Go to: <a href="http://kdecom.com" target="_blank">kdecom.com</a>
            </div>
          </div>
        </div>
      </div>
