<div id="header">
    <!-- Start Logo -->
    <a href="<?php echo APPLICATION_URL ?>">					
        <img id="logo" alt="KD Step Logo" width="60" src="<?php echo APPLICATION_URL ?>/public/global/images/your-logo.jpg"></a>

    <p class="sitename">Project Management Software</p>

    <div class="clear"></div>


    
</div>

<h1 class="demo-logo">
    <div class="logo"></div>
    Flat UI
    <small>Free Web User Interface Kit</small>
</h1>