<ul id='side-menu' class='nav'>
    
        <li id="dashboard" class="<?php echo ($this->child->dashboard === true) ? "select" : ""; ?>">
        	<a href="<?php echo $this->url('admin/default', array('action' => 'index', 'controller' => 'index')); ?>">
            	Dashboard
            </a>
        </li>
    
    
        <li id="users" class="<?php echo ($this->child->user === true) ? "select" : ""; ?>">
        	<a href="<?php echo $this->url('admin/default', array('action' => 'index', 'controller' => 'user')); ?>">
            	Logins
        	</a>
        </li>
    

    
        <!-- <li id="user-roles" class="<?php echo ($this->child->user_roles === true) ? "select" : ""; ?>">
        	<a href="<?php echo $this->url('admin/default', array('action' => 'index', 'controller' => 'role')); ?>">
            	User Roles
        	</a>
        </li>
    
    
        <li id="user-access" class="<?php echo ($this->child->user_access === true) ? "select" : ""; ?>">
        	<a href="<?php echo $this->url('admin/useraccess', array('action' => 'index', 'controller' => 'userAccess')); ?>">
            	User Access by Role
        	</a>
        </li>
    
    
        <li id="contact-type" class="<?php echo ($this->child->contact_type === true) ? "select" : ""; ?>">
        	<a href="<?php echo $this->url('admin/contacttype', array('action' => 'index', 'controller' => 'contact-type')); ?>">
            	Contact Type
        	</a>
        </li>
   
    
        <li id="contact" class="<?php echo ($this->child->contact === true) ? "select" : ""; ?>">
        	<a href="<?php echo $this->url('admin/contact', array('action' => 'index', 'controller' => 'contact')); ?>">
            	Contact
             </a> 
        </li>
   
    
        <li id="project-type" class="<?php echo ($this->child->projecttype === true) ? "select" : ""; ?>">
        	<a href="<?php echo $this->url('admin/projecttype', array('action' => 'index', 'controller' => 'project-type')); ?>">
            	Project Type
            </a> 
        </li>
    
    
        <li id="project" class="<?php echo ($this->child->project === true) ? "select" : ""; ?>">
        	<a href="<?php echo $this->url('admin/project', array('action' => 'index', 'controller' => 'project')); ?>">
            	Project
            </a> 
        </li>
    
     	 -->
        <li id="system_settings" class="<?php echo ($this->child->system_update === true) ? "select" : ""; ?>">
        	<a href="<?php echo $this->url('admin/default', array('action' => 'update', 'controller' => 'index')); ?>">
            	System Settings Edit
        	</a> 
        </li>
        
         <li>
                            <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Second Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Second Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
    
</ul>