<ul>
    <a href="<?php echo $this->url('admin/default', array('action' => 'index', 'controller' => 'index')); ?>">
        <li id="dashboard" class="<?php echo ($this->child->dashboard === true) ? "select" : ""; ?>">
            Dashboard
        </li>
    </a>
    <a href="<?php echo $this->url('admin/default', array('action' => 'index', 'controller' => 'user')); ?>">
        <li id="users" class="<?php echo ($this->child->user === true) ? "select" : ""; ?>">
            Logins
        </li>
    </a>

    <a href="<?php echo $this->url('admin/default', array('action' => 'index', 'controller' => 'role')); ?>">
        <li id="user-roles" class="<?php echo ($this->child->user_roles === true) ? "select" : ""; ?>">
            User Roles
        </li>
    </a>
    <a href="<?php echo $this->url('admin/useraccess', array('action' => 'index', 'controller' => 'userAccess')); ?>">
        <li id="user-access" class="<?php echo ($this->child->user_access === true) ? "select" : ""; ?>">
            User Access by Role
        </li>
    </a>
    <a href="<?php echo $this->url('admin/contacttype', array('action' => 'index', 'controller' => 'contact-type')); ?>">
        <li id="contact-type" class="<?php echo ($this->child->contact_type === true) ? "select" : ""; ?>">
            Contact Type
        </li>
    </a>
    <a href="<?php echo $this->url('admin/contact', array('action' => 'index', 'controller' => 'contact')); ?>">
        <li id="contact" class="<?php echo ($this->child->contact === true) ? "select" : ""; ?>">
            Contact 
        </li>
    </a>
    <a href="<?php echo $this->url('admin/projecttype', array('action' => 'index', 'controller' => 'project-type')); ?>">
        <li id="project-type" class="<?php echo ($this->child->projecttype === true) ? "select" : ""; ?>">
            Project Type 
        </li>
    </a>
    <a href="<?php echo $this->url('admin/project', array('action' => 'index', 'controller' => 'project')); ?>">
        <li id="project" class="<?php echo ($this->child->project === true) ? "select" : ""; ?>">
            Project 
        </li>
    </a>
     <a href="<?php echo $this->url('admin/default', array('action' => 'update', 'controller' => 'index')); ?>">
        <li id="system_settings" class="<?php echo ($this->child->system_update === true) ? "select" : ""; ?>">
            System Settings Edit 
        </li>
    </a>
</ul>
