<div class="row">
    <div class="span2"></div>
    <div class="span1">View</div>
    <div class="span1">Create/Edit</div>
    <div class="span1">Delete</div>
    
</div>
<div class="row access_box">
    <div class="span2 access_title">Employee</div>
    <div class="span1"><input type="checkbox" name="employee[view]" /></div>
    <div class="span1"><input type="checkbox" name="employee[create-edit]" /></div>
    <div class="span1"><input type="checkbox" name="employee[delete]" /></div>
</div>