<h2>Front End</h2>
<div class="container-fluid row">
    <div class="col-xs-2"></div>
    <div class="col-xs-2">View</div>
    <div class="col-xs-2">Create/Edit</div>
    <div class="col-xs-2">Delete</div>
    
</div>

<div class="container-fluid row access_box">
    <div class="col-xs-2 access_title">Employee</div>
    <div class="col-xs-2"><input type="checkbox" data-toggle="switch" name="access[employee][view]" /></div>
    <div class="col-xs-2"><input type="checkbox" data-toggle="switch" name="access[employee][create-edit]" /></div>
    <div class="col-xs-2"><input type="checkbox" data-toggle="switch" name="access[employee][delete]" /></div>
</div>

<h2>Admin</h2>

<div class="container-fluid row">
    <div class="col-xs-2"></div>
    <div class="col-xs-2">View</div>
    <div class="col-xs-2">Create/Edit</div>
    <div class="col-xs-2">Delete</div>
    
</div>
<div class="container-fluid row access_box">
    <div class="col-xs-2 access_title">Login</div>
    <div class="col-xs-2"><input type="checkbox" data-toggle="switch" name="access[user][index]" /></div>
    <div class="col-xs-2"><input type="checkbox" data-toggle="switch" name="access[user][update]" /></div>
    <div class="col-xs-2"><input type="checkbox" data-toggle="switch" name="access[user][delete]" /></div>
</div>