<div class="grid_content">
    
    <div class="Header_titles">
        <h1>Attribute</h1>
        <div class="add_link">
            <a href="<?php
                echo $this->url()
                        ->makeUrl(array(
                            'module' => 'admin',
                            'controller' => 'attribute',
                            'action' => 'edit'
                        ));
                ?>">Add Attribute</a>
        </div>
    </div>
    <div class="table">
        <div class="tr header_title">
            <div class="td">
                ID
            </div>
            <div class="td">
                Attribute Scope (unique)
            </div>
            <div class="td">
                Attribute title
            </div>
            <div class="td">
                Attribute Type
            </div>
            <div class="td">
                Attribute Belongs to
            </div>
            <div class="td">
                Edit
            </div>
            <div class="td">
                Delete
            </div>
        </div>

        <?php
        foreach ($this->paginator as $record) {
            ?>

            <div class="tr">
                <div class="td">
                    <?php
                    echo $record->id;
                    ?>
                </div>
                <div class="td">
                    <?php
                    echo $record->unique_key_attribute;
                    ?>
                </div>
                <div class="td">
                    <?php
                    echo $record->attribute_title;
                    ?>
                </div>
                <div class="td">
                    <?php
                    echo $record->attribute_type;
                    ?>
                </div>
                <div class="td">
                    <?php
                    echo $record->attribute_belongs_to;
                    ?>
                </div>
                <div class="td">
                    <a href="<?php
                echo $this->url()->makeUrl(array(
                                        'module' => 'admin',
                                        'controller' => 'attribute',
                                        'action' => 'edit',
                                        'id' => $record->id
                                    ));
                ?>" title="edit">edit</a>
                </div>
                <div class="td">
                    delete
                </div>
            </div>
            <?php
        }
        ?>

    </div>
    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml');
    ?>
</div>