<?php $this->headLink()->prependStylesheet($this->basePath() . '/public/module/application/timesheet.css'); ?>
<?php $this->headScript()->prependFile($this->basePath() . '/public/module/application/timesheet.js'); ?>
<h1 class="demo-logo">Timesheet</h1>


<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php $form->prepare(); ?>

<div class="timesheet_date">
    <?php echo $date; ?><a href="" class="change_date" >change date</a>
    <input name="task_date" type="text"  class="timesheet_date" value="<?php echo $date; ?>">    
</div>
<div class="row timesheet_label">
    <span class="start_time_label">Start Time</span>
    <span class="end_time_label">End Time</span>
    <span class="notes_label">Notes</span>
</div>
<div class="timesheet_rows_wrap">

    <?php
    if (count($timesheetRows) > 0) {
        
        foreach ($timesheetRows as $timesheetRow) {
            $startTime = date('G:i',strtotime($timesheetRow->start_time));
            $endTime = date('G:i',strtotime($timesheetRow->end_time));
            ?> 

            <div class="timesheet_row control-input">

                <input  	name="timesheet[<?php echo $userSessionData['id']; ?>][<?php echo $timesheetRow->id; ?>][id]" 
                		type="hidden"   value="<?php echo $userSessionData['id']; ?>" />    
                
              
                <input data-defaultTime='<?php echo $startTime;  ?>'
                	name="timesheet[<?php echo $userSessionData['id']; ?>][<?php echo $timesheetRow->id; ?>][start_time]" 
                	type="text" required="required" class="timepicker start_time" 
                      value="<?php echo $startTime; ?>" />    
                      
                <input 	data-defaultTime='<?php echo $endTime;  ?>'
                		name="timesheet[<?php echo $userSessionData['id']; ?>][<?php echo $timesheetRow->id; ?>][end_time]" 
                		type="time" required="required" class="timepicker end_time" 
                       value="<?php echo $endTime; ?>" />    
                       
                <input 	name="timesheet[<?php echo $userSessionData['id']; ?>][<?php echo $timesheetRow->id; ?>][notes]" 
                		type="text" required="required" class="notes" 
                       	value="<?php echo $timesheetRow->notes;  ?>" />
            </div>

            <?php
        }
    } else {
        ?>

        <div class="timesheet_row control-input">

            <input name="timesheet[<?php echo $userSessionData['id']; ?>][<?php echo $random; ?>][id]" type="hidden"  
            	 value="<?php echo $userSessionData['id']; ?>">    
            <input name="timesheet[<?php echo $userSessionData['id']; ?>][<?php echo $random; ?>][start_time]" 
            	type="text" required="required" class="timepicker start_time" value="">    
            <input name="timesheet[<?php echo $userSessionData['id']; ?>][<?php echo $random; ?>][end_time]" 
            	type="text" required="required" class="timepicker end_time" value="">    
            <input name="timesheet[<?php echo $userSessionData['id']; ?>][<?php echo $random; ?>][notes]" type="text" required="required" class="notes" value="">
        </div>
    <?php } ?>

</div>
<div class="addlink control-input">
    <a href="" title="add new" >Add New </a>
</div>
<div class="control-input btn-block ">
    <label>&nbsp;</label>
    <div class="btn btn-large  btn-success span2">
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
    <div class="btn btn-large  btn-success span2">
        <?php echo $this->formRow($form->get('save_close')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
