<table cellspacing="0" cellpadding="0" border="0" width="90%">
    <tbody><tr>
            <td width="10%"></td>
            <td align="left" width="90%" style="font:13px/18px Arial, sans-serif">

            <table cellspacing="0" cellpadding="0" border="0" width="100%" style="font:13px/18px Arial, sans-serif">
                <tbody><tr>
                    <td style="padding-right:30px">
                        <h2 style="font:normal 20px/20px Arial, sans-serif;padding:0 0 18px;color:black">
                            You're ready to start using KD Tips!
                        </h2>
                        <br>
                        <div>
                            Newsflash - There is a heaps of stuff you can do here would you like to go on
                            <a target="_blank" style="color:#2e6ace" href="<?php echo APPLICATION_URL; ?>">
                                KD Tips
                            </a>
                            and find out more!
                        </div>
                        <br>

                        Try these tips:
                        <br>
                        <br>
                        <table cellspacing="0" cellpadding="0" border="0" width="100%"
                               style="font:13px/18px Arial, sans-serif;color:#666666">
                            <tbody><tr>
                                    
                                    <td valign="top" style="padding:10px 0 15px">
                                        <ul>
                                            <li>Email: <?php echo $this->data['user_email']; ?></li>
                                            <li>Your Temp Password is: <?php echo $this->data['password']; ?></li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr>
                                    <td valign="top" style="padding:10px 0 15px">
                                        We would recommend you to changed your password asap.
                                        <br/>
                                         <a target="_blank" style="color:#2e6ace" href="<?php echo APPLICATION_URL."/user/login" ?>">
                                            Login Here to changed Your Password
                                        </a>
                                    </td>
                                </tr>
                            </tbody></table>

                    </td>
                    
                </tr></tbody>
            </table>
                <br>
                <br>
                <br>
                Good Luck!<br>
                The KD Tips Team
            </td>
        </tr>
    </tbody></table>