<table cellspacing="0" cellpadding="0" border="0" width="80%">
    <tbody><tr>
            <td width="10%"></td>
            <td align="left" width="90%" style="font:13px/18px Arial, sans-serif">
                <h2 style="font:normal 24px/27px Arial, sans-serif;padding:0 0 18px;color:black">
                    Reset your password on TagMyJob?
                </h2>
                
                <br>
                <big style="font:16px/18px Arial, sans-serif">
                    <b>
                        
                        Email :- <?php echo $this->data['email']; ?>
                        Password:- <?php echo $this->data['password']; ?>
                        
                    </b>
                </big><br>
                <br>
                This email is send to your because you request a new password.<br>
                <br>
                Thank you,<br>
                The TagMyJob Team

                <br><br>
               
            </td>
        </tr>
    </tbody></table>