<table cellspacing="0" cellpadding="0" border="0" width="80%">
    <tbody>
        <tr>
            <td width="10%"></td>
            <td align="left" width="90%" style="font:13px/18px Arial, sans-serif">
                <table cellspacing="0" cellpadding="0" border="0" width="100%">
                    <tbody><tr>
                            <td style="font:13px/18px Arial, sans-serif;background:#fffbba;border:1px solid #ffc610;
                                padding:15px">
                                <h2 style="font:normal 20px/20px Arial, 
                                    sans-serif;color:black">
                                    You're almost there...
                                </h2>
                                <div>To complete your KD Tips registration, please click this link:</div>
                                
                            </td>
                        </tr>
                    </tbody></table>
                <br>
                This email is a part of the procedure to register on the system, 
                if you did not request registration on KD Tips, please, email us.
                <br>
                <br>
                Good Luck!<br>
                The KD Tips Team
                <br><br>
            </td>
        </tr>
    </tbody></table>
<!--
SUbJect:- Complete Your TagMyJob Register

You're almost there...

To complete your TagMyJob registration, please click this link:

<a href=''><h1>Complete your registration</h1></a>

This email is a part of the procedure to register on the system, if you did not request registration on TagMyJob,
please, ignore this email. After a short time the request will be removed from the system.

Have fun!
The TagMyJob Team

This is a post-only mailing. Replies to this message are not monitored or answered.


-->