<table cellspacing="0" cellpadding="0" border="0" width="90%">
    <tbody><tr>
            <td width="10%"></td>
            <td align="left" width="90%" style="font:13px/18px Arial, sans-serif">

            <table cellspacing="0" cellpadding="0" border="0" width="100%" style="font:13px/18px Arial, sans-serif">
                <tbody><tr>
                    <td style="padding-right:30px">
                        <h2 style="font:normal 20px/20px Arial, sans-serif;padding:0 0 18px;color:black">
                            You're ready to start using TagMyJob!
                        </h2>
                        <br>
                        <div>
                            Newsflash - There is a heaps of job that you are looking for please go to
                            <a target="_blank" style="color:#2e6ace" href="<?php echo APPLICATION_URL; ?>">
                                TagMyJob
                            </a>
                            and find out more!
                        </div>
                        <br>

                        Try these tips:
                        <br>
                        <br>
                        <table cellspacing="0" cellpadding="0" border="0" width="100%"
                               style="font:13px/18px Arial, sans-serif;color:#666666">
                            <tbody><tr>
                                    <td align="center" width="20%" valign="top"
                                        style="padding:10px 10px 15px 10px">
                                        <img width="16" height="13" alt="" src="">
                                    </td>
                                    <td valign="top" style="padding:10px 0 15px">
                                        <a target="_blank" style="color:#2e6ace" href="<?php echo APPLICATION_URL."/job/list" ?>">
                                            Looking for a Job
                                        </a>
                                        <br>
                                        Upload Your CV on TagMyJob.
                                    </td>
                                </tr>
                            </tbody></table>

                    </td>
                    
                </tr></tbody>
            </table>
                <br>
                <br>
                <br>
                Good Luck!<br>
                The TagMyJob Team
            </td>
        </tr>
    </tbody></table>