<?php
echo $this->headLink()->prependStylesheet(APPLICATION_URL . '/public/application/user/login.css');
//$this->headScript()->prependFile(APPLICATION_URL . '/public/application/user/login.js');
?>

<form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>" class="login-here">
    <h1 class="login-here-title">Login Here</h1>
    <?php
    echo $this->form->getDisplayGroup('FormElemts');
    echo $this->form->getDisplayGroup('buttons');
    ?>
</form>


<div class="login">
    <div class="login-screen">
        <div class="login-icon">
            <img src="images/login/icon.png" alt="Welcome to Mail App" />
            <h4>Welcome to <small>Mail App</small></h4>
        </div>

        <div class="login-form">
            <div class="control-group">
                <input type="text" class="login-field" value="" placeholder="Enter your name" id="login-name" />
                <label class="login-field-icon fui-user" for="login-name"></label>
            </div>

            <div class="control-group">
                <input type="password" class="login-field" value="" placeholder="Password" id="login-pass" />
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>

            <a class="btn btn-primary btn-large btn-block" href="#">Login</a>
            <a class="login-link" href="#">Lost your password?</a>
        </div>
    </div>
</div>
