<h1>
    <?php echo $title; ?>
</h1><?php

$form->prepare();
echo $this->form()->openTag($form);?>
<div class="alert danger">
   <?php echo $error; ?>
</div>
        <div class="control-input">
            <?php echo $this->formRow($form->get('old_password'));?>
        </div>
        <div class="control-input">
            <?php echo $this->formRow($form->get('new_password'));?>
        </div>
        <div class="control-input">
            <?php echo $this->formRow($form->get('c_new_password'));?>
        </div>
        <div class="control-input">
                <label>&nbsp;</label>
            <div class="submit-input">
                <?php echo $this->formRow($form->get('submit'));?>
            </div>
        </div>
<?php echo $this->form()->closeTag();?>