<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('KD Step');

echo $this->doctype('HTML5');
?>
<!DOCTYPE html>
<html  xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <link rel="shortcut icon" href="<?php echo APPLICATION_URL . '/public/global/images/favicon.ico'; ?>" type="image/x-icon">


            <?php $this->headLink()->prependStylesheet(APPLICATION_URL . '/public/global/css/jquery-ui-1.10.0.custom.min.css'); ?>
            <?php echo $this->headLink()->prependStylesheet(APPLICATION_URL . '/public/bootstrap/css/bootstrap.css'); ?>
            <?php echo $this->headLink()->prependStylesheet(APPLICATION_URL . '/public/css/flat-ui.css'); ?>



            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/js/jquery.stacktable.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/js/jquery.placeholder.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/js/jquery.tagsinput.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/js/flatui-radio.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/js/flatui-checkbox.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/js/bootstrap-switch.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/js/bootstrap-select.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/js/bootstrap.min.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/js/jquery.ui.touch-punch.min.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/application/default/Home.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/global/js/jquery-ui-timepicker-addon.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/global/js/jquery-ui-sliderAccess.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/global/js/jquery-ui-1.10.0.custom.min.js'); ?>
            <?php echo $this->headScript()->prependFile(APPLICATION_URL . '/public/global/js/jquery-1.9.0.js'); ?>
            
          
            <script src="http://vjs.zencdn.net/c/video.js"></script>


            <meta name="viewport" content="width=device-width, initial-scale=1.0" />


            <!-- Loading Flat UI -->
            <link href="" rel="stylesheet" />

            <link rel="shortcut icon" href="images/favicon.ico" />

            <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
            <!--[if lt IE 9]>
              <script src="js/html5shiv.js"></script>
            <![endif]-->

    </head>
    <body>


        <div id="page-wrap">
            <div class="PageWrapper">

                <div class="HeaderContainer">
                    <div class="HeaderContent">
                        <?php echo $this->render('layout-v1/header.phtml'); ?>

                    </div>
                </div>


                <div class="BreadCrmp">
                    You are in: <?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render(); ?>
                </div>
                <div class="MiddleContainer">
                    <div id="content" class="clearfix">
                        <div id="content-area">
                            <?php echo $this->layout()->content; ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="HomeFooterWrapper">
                <div class="Footer">
                    <?php echo $this->render('layout-v1/footer.phtml'); ?>
                </div>
            </div>
        </div>
    </body>
</html>