<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('KD Step');

echo $this->doctype('HTML5');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <link rel="shortcut icon" href="<?php echo APPLICATION_URL . '/public/global/images/favicon.ico'; ?>" type="image/x-icon">


            <?php $this->headLink()->prependStylesheet(APPLICATION_URL . '/public/global/css/jquery-ui-1.8.16.custom.css'); ?>
            <?php echo $this->headLink()->prependStylesheet(APPLICATION_URL . '/public/global/css/theme1.css'); ?>

            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/application/default/Home.js'); ?>
            <?php $this->headScript()->prependFile(APPLICATION_URL . '/public/global/js/jquery-ui-1.8.16.custom.min.js'); ?>
            <?php echo $this->headScript()->prependFile(APPLICATION_URL . '/public/global/js/jquery-1.7.1.js'); ?>

    </head>
    <body>


        <div id="page-wrap">
            <div class="PageWrapper">

                <div class="HeaderContainer">
                    <div class="HeaderContent">
                        <?php echo $this->render('layout-v1/header.phtml'); ?>

                    </div>
                </div>


                <div class="BreadCrmp">
                    You are in: <?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render(); ?>
                </div>
                <div class="MiddleContainer">
                    <?php echo $this->layout()->content; ?>
                    <?php echo $this->render('layout-v1/sidebar.phtml'); ?>
                </div>
            </div>
            <div class="HomeFooterWrapper">
                <div class="Footer">
                    <?php echo $this->render('layout-v1/footer.phtml'); ?>
                </div>
            </div>
        </div>
    </body>
</html>