<div class="grid_content">
    
    <div class="Header_titles">
        <h1>Projects</h1>
        <div class="add_link">
            <a href="<?php
                echo $this->url()
                        ->makeUrl(array(
                            'module' => 'workflow',
                            'controller' => 'project',
                            'action' => 'edit'
                        ));
                ?>">Add Project</a>
        </div>
    </div>
    <div class="table">
        <div class="tr header_title">
            <div class="td">
                ID
            </div>
            <div class="td">
                Project Name
            </div>
            <div class="td">
                Project Description
            </div>
            <div class="td">
                View
            </div>
            <div class="td">
                Edit
            </div>
            <div class="td">
                Delete
            </div>
        </div>

        <?php
        foreach ($this->paginator as $record) {
            ?>

            <div class="tr">
                <div class="td">
                    <?php
                    echo $record->id;
                    ?>
                </div>
                <div class="td">
                    <?php
                    echo $record->project_name;
                    ?>
                </div>
                <div class="td">
                    <?php
                    echo $record->project_description;
                    ?>
                </div>
                <div class="td">
                    <a href="<?php
                echo $this->url()->makeUrl(array(
                                        'module' => 'workflow',
                                        'controller' => 'project',
                                        'action' => 'view',
                                        'id' => $record->id
                                    ));
                ?>" title="edit">View</a>
                </div>
                <div class="td">
                    <a href="<?php
                echo $this->url()->makeUrl(array(
                                        'module' => 'workflow',
                                        'controller' => 'project',
                                        'action' => 'edit',
                                        'id' => $record->id
                                    ));
                ?>" title="edit">edit</a>
                </div>
                <div class="td">
                    delete
                </div>
            </div>
            <?php
        }
        ?>

    </div>
    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml');
    ?>
</div>