<?php
// /StickfNotes/view/sticky-notes/sticky-notes/index.phtml
?>

<div id="coresystemsettings" class="span12">
    <div class="span3">
        <h3>User Management</h3>
        <ul>
            <li>
                <a href="<?php echo $this->url('admin/default', array('action' => 'update', 'controller' => 'user', 'id' => $userSessionData['id'])); ?>" title="User Profile" >
                    User Profiles
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('admin/default', array('action' => 'update', 'controller' => 'role', 'id' => $userSessionData['id'])); ?>" title="Roles Profile" >
                    Roles Profiles
                </a>
            </li>
        </ul>
    </div>
    <div class="span8">
        <?php foreach ($coresystemsettings as $settings): ?>
            <div class="core-system-settings">
                <h3><?php echo $settings->getApplicationName(); ?></h3>
                <p><a href="<?php echo $this->url('admin/default', array('action' => 'update', 'controller' => 'index', 'id' => 1)); ?>" >EDIT</a></p>
            </div>
        <?php endforeach; ?>

    </div>
</div>
<div class="clear-both"></div>