<?php
// /StickfNotes/view/sticky-notes/sticky-notes/index.phtml
?>

<div id="coresystemsettings" class="span12">
    
    <div class="span8">
        <?php foreach ($coresystemsettings as $settings): ?>
            <div class="core-system-settings">
                <h3><?php echo $settings->getApplicationName(); ?></h3>
                <p><a href="<?php echo $this->url('admin/default', array('action' => 'update', 'controller' => 'index', 'id' => 1)); ?>" >EDIT</a></p>
            </div>
        <?php endforeach; ?>

    </div>
</div>
<div class="clear-both"></div>