
<?php $this->headLink()->prependStylesheet($this->basePath() . '/public/module/application/dashboard.css'); ?>

<div class="hero-unit">
    <h1>KD Project Managemeny System</h1>
</div>

<div class="row">

    <div class="span2 profile">
        
        <div class="row-fluid">
            <h3>User Info</h3>
            <p><?php echo $userSessionData['first_name']; ?> <?php echo $userSessionData['last_name']; ?></p>
        </div>
        
        <div class="profile_image">
            <img src="" alt="Name" />
        </div>
        
    </div>

    <div class="span10">
        <h2>What's On now</h2>
   </div>

  
</div>
